# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_widget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphWidget(object):
    def setupUi(self, GraphWidget):
        GraphWidget.setObjectName("GraphWidget")
        GraphWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(GraphWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.control_panel = QtWidgets.QWidget(GraphWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_panel.sizePolicy().hasHeightForWidth())
        self.control_panel.setSizePolicy(sizePolicy)
        self.control_panel.setObjectName("control_panel")
        self.control_panel_layout = QtWidgets.QHBoxLayout(self.control_panel)
        self.control_panel_layout.setContentsMargins(0, 0, 0, 0)
        self.control_panel_layout.setObjectName("control_panel_layout")
        self.channel_container = QtWidgets.QWidget(self.control_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel_container.sizePolicy().hasHeightForWidth())
        self.channel_container.setSizePolicy(sizePolicy)
        self.channel_container.setObjectName("channel_container")
        self.channel_container_layout = QtWidgets.QHBoxLayout(self.channel_container)
        self.channel_container_layout.setContentsMargins(0, 0, 0, 0)
        self.channel_container_layout.setSpacing(0)
        self.channel_container_layout.setObjectName("channel_container_layout")
        self.control_panel_layout.addWidget(self.channel_container)
        self.graph_container = QtWidgets.QWidget(self.control_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_container.sizePolicy().hasHeightForWidth())
        self.graph_container.setSizePolicy(sizePolicy)
        self.graph_container.setObjectName("graph_container")
        self.graph_container_layout = QtWidgets.QHBoxLayout(self.graph_container)
        self.graph_container_layout.setContentsMargins(0, 0, 0, 0)
        self.graph_container_layout.setSpacing(0)
        self.graph_container_layout.setObjectName("graph_container_layout")
        self.control_panel_layout.addWidget(self.graph_container)
        spacerItem = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.control_panel_layout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.control_panel)
        self.pw = PlotWidget(GraphWidget)
        self.pw.setObjectName("pw")
        self.verticalLayout.addWidget(self.pw)

        self.retranslateUi(GraphWidget)
        QtCore.QMetaObject.connectSlotsByName(GraphWidget)

    def retranslateUi(self, GraphWidget):
        _translate = QtCore.QCoreApplication.translate
        GraphWidget.setWindowTitle(_translate("GraphWidget", "Form"))
from pyqtgraph import PlotWidget
