# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_group_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphGroup(object):
    def setupUi(self, GraphGroup):
        GraphGroup.setObjectName("GraphGroup")
        GraphGroup.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(GraphGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QWidget(GraphGroup)
        self.container.setObjectName("container")
        self.containe_grid_layout = QtWidgets.QGridLayout(self.container)
        self.containe_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.containe_grid_layout.setObjectName("containe_grid_layout")
        self.verticalLayout.addWidget(self.container)

        self.retranslateUi(GraphGroup)
        QtCore.QMetaObject.connectSlotsByName(GraphGroup)

    def retranslateUi(self, GraphGroup):
        _translate = QtCore.QCoreApplication.translate
        GraphGroup.setWindowTitle(_translate("GraphGroup", "Form"))
