# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'group_tab_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupTab(object):
    def setupUi(self, GroupTab):
        GroupTab.setObjectName("GroupTab")
        GroupTab.resize(662, 481)
        self.gridLayout = QtWidgets.QGridLayout(GroupTab)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter1 = QtWidgets.QSplitter(GroupTab)
        self.splitter1.setOrientation(QtCore.Qt.Vertical)
        self.splitter1.setObjectName("splitter1")
        self.splitter2 = QtWidgets.QSplitter(self.splitter1)
        self.splitter2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter2.setObjectName("splitter2")
        self.control_panel = QtWidgets.QListWidget(self.splitter2)
        self.control_panel.setObjectName("control_panel")
        self.history_containter = QtWidgets.QWidget(self.splitter2)
        self.history_containter.setObjectName("history_containter")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.history_containter)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.history_control_panel = QtWidgets.QWidget(self.history_containter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_control_panel.sizePolicy().hasHeightForWidth())
        self.history_control_panel.setSizePolicy(sizePolicy)
        self.history_control_panel.setObjectName("history_control_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.history_control_panel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.load_button = QtWidgets.QPushButton(self.history_control_panel)
        self.load_button.setObjectName("load_button")
        self.verticalLayout_2.addWidget(self.load_button)
        self.save_button = QtWidgets.QPushButton(self.history_control_panel)
        self.save_button.setObjectName("save_button")
        self.verticalLayout_2.addWidget(self.save_button)
        self.delete_button = QtWidgets.QPushButton(self.history_control_panel)
        self.delete_button.setObjectName("delete_button")
        self.verticalLayout_2.addWidget(self.delete_button)
        self.horizontalLayout_2.addWidget(self.history_control_panel)
        self.history_list = QtWidgets.QListWidget(self.history_containter)
        self.history_list.setObjectName("history_list")
        self.horizontalLayout_2.addWidget(self.history_list)
        self.gridLayout.addWidget(self.splitter1, 0, 0, 1, 1)

        self.retranslateUi(GroupTab)
        QtCore.QMetaObject.connectSlotsByName(GroupTab)

    def retranslateUi(self, GroupTab):
        _translate = QtCore.QCoreApplication.translate
        GroupTab.setWindowTitle(_translate("GroupTab", "Form"))
        self.load_button.setText(_translate("GroupTab", "←"))
        self.save_button.setText(_translate("GroupTab", "→"))
        self.delete_button.setText(_translate("GroupTab", "X"))
